In [4]:
import numpy as np

### set seed

In [18]:
np.random.seed(66)
np.random.rand(3)

array([0.15428758, 0.13369956, 0.36268547])

In [23]:
np.random.seed(55)
np.random.rand(3)

array([0.09310829, 0.97165592, 0.48385998])

In [15]:
np.random.seed()
np.random.rand(3)

array([0.59818609, 0.41322973, 0.03428921])

### set random state which is independent from the global seed

In [5]:
rs = np.random.RandomState(23)
rs.rand(10)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009])

In [10]:
rs = np.random.RandomState(321)
rs.rand(3)

array([0.88594794, 0.07791236, 0.97964616])

### generate a random sample from interval [0, 1) in a given shape

In [6]:
# generate a random scalar
print(np.random.rand())  # from zero to one    

0.6791088754456315


In [10]:
# generate a random scalar
print(np.random.rand() * 10)      

5.576185895623528


In [15]:
# generate a random scalar
print(int(np.random.rand() * 10))      

2


In [19]:
# generate a random scalar
print(np.random.rand() * 100) 

51.445118498405805


In [26]:
# generate a 1-D array
print(np.random.rand(10) )
print(type(np.random.rand(10)))

[0.66432752 0.63405676 0.35341947 0.02664251 0.16528984 0.87931899
 0.06782046 0.3690858  0.11550059 0.09629414]
<class 'numpy.ndarray'>


In [18]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.53910547 0.66432752 0.63405676]
 [0.35341947 0.02664251 0.16528984]
 [0.87931899 0.06782046 0.3690858 ]]


In [27]:
# generate a 3-D array
print(np.random.rand(3,3,3))

[[[0.30404453 0.18826767 0.12615963]
  [0.41421683 0.9446711  0.03834352]
  [0.95704009 0.12631581 0.0779476 ]]

 [[0.16608301 0.9547679  0.26806126]
  [0.10054094 0.90777618 0.55337468]
  [0.74869262 0.10672348 0.78641439]]

 [[0.65877773 0.36195657 0.64985479]
  [0.23054335 0.71685851 0.2661214 ]
  [0.62279616 0.81430885 0.03937529]]]


In [28]:
# generate a 4-D array
print(np.random.rand(3,3,3,3))          

[[[[5.91262143e-01 3.21387831e-01 5.11416280e-01]
   [5.03405841e-01 3.11063956e-01 9.07980825e-01]
   [2.74152625e-01 8.18676180e-01 5.52782565e-01]]

  [[6.47089825e-01 7.02874382e-01 4.11805810e-01]
   [8.98347961e-01 6.41083171e-02 6.64467733e-01]
   [3.16882748e-01 7.03736931e-01 7.70374642e-01]]

  [[4.18003926e-01 8.92316485e-02 2.33518873e-01]
   [7.59518707e-01 4.69182143e-01 2.02953722e-01]
   [6.96093851e-01 9.09948634e-01 5.82322805e-02]]]


 [[[7.88587264e-01 3.95683764e-01 8.15125530e-01]
   [5.66379461e-01 3.99532570e-01 6.98900921e-01]
   [5.86129915e-01 5.48260640e-01 5.13352940e-04]]

  [[5.58941164e-01 5.54009148e-01 2.99056732e-01]
   [2.16054328e-01 1.25615479e-01 6.47052919e-01]
   [4.69024537e-01 7.97958857e-01 1.29142911e-02]]

  [[8.69272440e-01 3.71849961e-01 7.52543552e-01]
   [8.67430469e-01 2.40413738e-01 4.95077760e-01]
   [8.19241343e-01 8.23460428e-01 5.82590357e-01]]]


 [[[2.20496711e-01 4.65118990e-01 2.68446802e-01]
   [6.62640093e-01 6.02580844e-01 

### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [26]:
print(np.random.randn(3,3))

[[ 1.60762261  0.34502972  0.19466217]
 [-0.26729125 -1.22087721  1.40425451]
 [-1.21532397  0.67588651 -0.98335124]]


### generate an array of random integers in a given interval [low, high)

In [20]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[9 3 8]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [28]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print()
print(np.random.random(10))
print()
print(np.random.ranf(10))
print()
print(np.random.sample(10))

[0.43272219 0.4409926  0.41830042 0.12510184 0.23433741 0.38529304
 0.41147671 0.49555814 0.88650583 0.96566402]

[0.18335173 0.57615175 0.14656317 0.3198636  0.66461515 0.39455975
 0.45229316 0.96282936 0.21565009 0.21784078]

[0.12401236 0.61865406 0.26324531 0.26834124 0.49593699 0.17505415
 0.2107553  0.38733881 0.87903361 0.74352249]

[0.73629731 0.48220734 0.83973717 0.75215987 0.50590132 0.47783335
 0.06525612 0.15593831 0.12941788 0.04582272]


### generate a random sample from a given 1-D array

In [27]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.3, 0.6]))

[2 2 2 2 2 2 0 2 2 2]


In [45]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.4, 0.4, 0.2]))

[1 1 1 2 0 1 2 0 0 0]


In [25]:
print(np.random.choice(3, 10))

[0 1 1 0 1 0 1 2 2 0]


In [48]:
print(np.random.choice([1,2,3], 10))

[2 3 2 1 1 3 3 2 3 2]


### shuffle an array in place

In [22]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
np.random.shuffle(arr)
print(arr)

[5 1 8 4 6 3 0 2 7 9]


### generate a permutation of an array

In [24]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [9 3 0 8 7 4 2 6 1 5]
