In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)
arr

array([[0.32075897, 0.32479573, 0.64816778, 0.46071548, 0.67969232],
       [0.42664215, 0.241982  , 0.20092149, 0.27095483, 0.99452742],
       [0.03003101, 0.5164804 , 0.48286694, 0.76645324, 0.88903558],
       [0.57367264, 0.83181623, 0.18826016, 0.87859777, 0.04773419],
       [0.532903  , 0.38310071, 0.11520815, 0.91256143, 0.15236344]])

### element-wise addition, subtraction, multiplication and division

In [4]:
print(arr + 10)
print()
print(arr - 10)
print()
print(arr * 10)
print()
print(arr / 10)

[[10.36520315 10.14002948 10.32671536 10.90246944 10.40790343]
 [10.56042917 10.88899044 10.24073532 10.51234433 10.46964386]
 [10.60038623 10.65996261 10.16667633 10.68757035 10.50975363]
 [10.75156859 10.77046029 10.13185365 10.52231003 10.91158626]
 [10.5972015  10.97839553 10.8847643  10.90894003 10.44469332]]

[[-9.63479685 -9.85997052 -9.67328464 -9.09753056 -9.59209657]
 [-9.43957083 -9.11100956 -9.75926468 -9.48765567 -9.53035614]
 [-9.39961377 -9.34003739 -9.83332367 -9.31242965 -9.49024637]
 [-9.24843141 -9.22953971 -9.86814635 -9.47768997 -9.08841374]
 [-9.4027985  -9.02160447 -9.1152357  -9.09105997 -9.55530668]]

[[3.65203147 1.40029477 3.26715356 9.02469438 4.07903427]
 [5.6042917  8.88990436 2.40735315 5.12344326 4.69643855]
 [6.00386233 6.59962611 1.66676334 6.87570347 5.09753627]
 [7.51568592 7.70460294 1.3185365  5.22310027 9.11586262]
 [5.97201502 9.78395526 8.84764303 9.08940028 4.44693322]]

[[0.03652031 0.01400295 0.03267154 0.09024694 0.04079034]
 [0.05604292 0.0

In [5]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
x = np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [2,1,12], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 7 10  1]
[ 7 20  3]


### element-wise exponentiation

In [4]:
print(np.exp(arr))

[[1.65529819 1.04025389 1.6782037  1.00539798 2.14692074]
 [1.26794974 1.71224599 2.67560762 1.49659368 1.08823404]
 [2.35011188 1.27162025 1.44043059 1.05294387 1.24056768]
 [1.66209918 1.05680009 1.47869681 1.53913911 2.27258786]
 [1.20518356 1.14731731 1.18932689 1.04600339 2.16967814]]


### element-wise logorithm

In [5]:
# natural log ( base e )
print(np.log(arr)) 

[[-0.68521637 -3.23234603 -0.658313   -5.22442354 -0.2691422 ]
 [-1.43800367 -0.62025747 -0.01595002 -0.90834329 -2.47033841]
 [-0.15728216 -1.42590095 -1.00801659 -2.96442888 -1.53447386]
 [-0.67711367 -2.89596728 -0.93863561 -0.84112936 -0.19733058]
 [-1.6786171  -1.98466647 -1.75222625 -3.10161282 -0.25543584]]


In [6]:
# base 2
print(np.log2(arr))     

[[-0.98855826 -4.66328958 -0.9497449  -7.53724994 -0.38829012]
 [-2.07460076 -0.89484237 -0.02301102 -1.31046236 -3.56394498]
 [-0.22691019 -2.05714023 -1.45426054 -4.27676684 -2.21377783]
 [-0.97686853 -4.17799763 -1.35416494 -1.21349316 -0.28468785]
 [-2.42173257 -2.86326847 -2.52792812 -4.47468143 -0.36851602]]


In [7]:
# base 10
print(np.log10(arr))    

[[-0.29758569 -1.40379004 -0.2859017  -2.26893832 -0.11688697]
 [-0.62451706 -0.2693744  -0.00692701 -0.39448848 -1.07285434]
 [-0.06830677 -0.61926091 -0.43777604 -1.2874351  -0.66641353]
 [-0.29406673 -1.25770261 -0.40764427 -0.36529784 -0.08569958]
 [-0.72901414 -0.8619297  -0.76098219 -1.34701333 -0.11093438]]


### element-wise square root

In [4]:
print(np.sqrt(arr))

[[0.84170664 0.99712459 0.89303808 0.91490252 0.80626664]
 [0.60795478 0.75441316 0.42179893 0.39268775 0.94972487]
 [0.9001505  0.6297466  0.77159573 0.82984387 0.65263596]
 [0.77422187 0.89838718 0.95842604 0.98581007 0.76386174]
 [0.40434462 0.71533625 0.73532568 0.80970994 0.78337234]]


### element-wise sine and cosine

In [5]:
print(np.sin(arr))

[[0.65067276 0.83835442 0.71562397 0.7426686  0.60523887]
 [0.36125088 0.53890716 0.17697722 0.15359327 0.7845545 ]
 [0.72447395 0.38626676 0.56080682 0.63548835 0.41317124]
 [0.56416327 0.72228425 0.79474084 0.82591404 0.55093548]
 [0.16276717 0.48966539 0.51473957 0.60965889 0.57587352]]


In [6]:
print(np.cos(arr))

[[0.75935825 0.54512556 0.69848575 0.66965913 0.79604391]
 [0.93246866 0.84236517 0.98421495 0.98813415 0.62005986]
 [0.68930219 0.92238711 0.82794668 0.77211046 0.91065335]
 [0.82566325 0.69159631 0.60694893 0.56379606 0.83454784]
 [0.98666451 0.87191043 0.85734659 0.79266388 0.8175388 ]]


### sum along a specified axis

In [3]:
# sum along the row
print(np.sum(arr, axis=0)) # 5 * 5 --> 5 sum    

[1.88400778 2.29817506 1.63542452 3.28928274 2.76335295]


In [4]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.43413027 2.13502789 2.68486717 2.52008099 2.09613674]


In [7]:
print(np.sum(arr))

14.340586603207418


### compute the min and max along a specified axis

In [11]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.16349458 0.39658078 0.17791433 0.15420367 0.4259337 ]


In [12]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.99425745 0.90197732 0.81027092 0.9718215  0.65563019]


In [13]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9942574525030909
0.154203672317354


### compute the indices of the min and max along a specified axis

In [17]:
arr

array([[0.50398117, 0.0394648 , 0.517724  , 0.00538346, 0.7640346 ],
       [0.23740122, 0.53780595, 0.9841765 , 0.40319164, 0.08455624],
       [0.85446293, 0.24029187, 0.36494209, 0.05158993, 0.21556908],
       [0.50808137, 0.05524556, 0.39116117, 0.43122324, 0.82091921],
       [0.18663189, 0.13742644, 0.17338751, 0.0449766 , 0.77457883]])

In [18]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[4 0 4 0 1]
[2 1 1 3 3]


In [19]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[3 4 3 1 3]
[4 2 0 4 4]


In [20]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

3
7


In [21]:
arr

array([[0.50398117, 0.0394648 , 0.517724  , 0.00538346, 0.7640346 ],
       [0.23740122, 0.53780595, 0.9841765 , 0.40319164, 0.08455624],
       [0.85446293, 0.24029187, 0.36494209, 0.05158993, 0.21556908],
       [0.50808137, 0.05524556, 0.39116117, 0.43122324, 0.82091921],
       [0.18663189, 0.13742644, 0.17338751, 0.0449766 , 0.77457883]])

### compute element-wise min and max of two arrays

In [24]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [26]:
print(20 / 3)
x = 20/3
x = str(x)
print(x.split("."))
anas = x.split(".")[1]
print(f"fraction = {anas}")
x = int(x[2:])

print(x)
print (20 // 3)

6.666666666666667
['6', '666666666666667']
fraction = 666666666666667
666666666666667
6


In [27]:
y= ((20/3)-(20 // 3))
print(y)
x = (len(str((20/3)-(20 // 3)))-2)
print(int((10**x) * y))

0.666666666666667
666666666666667


In [28]:
20 % 3

2

In [15]:
arr1 = np.random.rand(10) * 10

print(arr1)
print()
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

[5.65337024 9.20017535 3.61615494 3.67143396 3.74841939 3.98469219
 2.53330776 1.5128947  1.26567116 8.23973139]

fractional:  [0.65337024 0.20017535 0.61615494 0.67143396 0.74841939 0.98469219
 0.53330776 0.5128947  0.26567116 0.23973139]
integral:  [5. 9. 3. 3. 3. 3. 2. 1. 1. 8.]


In [24]:
newarr = np.array([1.23,])
re , intg  = np.modf(newarr)

# rounding the number to get the accurate reuslt
fraction = round(float(re), 2)
integer = int(intg)
print(fraction)
print(integer)

0.23
1


### compute the mean

In [22]:
# compute the overall mean
print(np.mean(arr))

0.3731282930060945


In [23]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.45811172 0.20204693 0.48627825 0.18727298 0.53193159]


In [24]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.36611761 0.44942631 0.34537118 0.44132611 0.26340026]


### compute the median

In [25]:
# compute the overall median
x = [1,2,4,6,7,8,9,12, 20]
print(np.median(x))

7.0


In [26]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.50398117 0.13742644 0.39116117 0.05158993 0.7640346 ]


In [27]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.50398117 0.40319164 0.24029187 0.43122324 0.17338751]


### compute the percentile

In [26]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.06324113 0.68166079 0.98234324]


### compute the standard deviation & variance

In [27]:
# compute the overall standard deviation
print(np.std(arr))

0.31691421921254487


In [28]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.40651498 0.22925625 0.24713125 0.37487395 0.16827072]


In [29]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.24361673 0.31067439 0.19733453 0.36364029 0.34314561]


In [30]:
# compute the overall variance
print(np.var(arr))

0.10043462233909695


In [31]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.16525443 0.05255843 0.06107385 0.14053048 0.02831504]


In [32]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.05934911 0.09651858 0.03894092 0.13223426 0.11774891]


### compute the covariance & correlation

In [33]:
arr = np.random.rand(5,8)
arr

array([[0.04064895, 0.89118294, 0.29135691, 0.81655582, 0.26134072,
        0.36155554, 0.06299668, 0.758472  ],
       [0.49546723, 0.76564698, 0.53060514, 0.19441138, 0.41685174,
        0.60150772, 0.20362636, 0.44151339],
       [0.16392179, 0.59051272, 0.64007483, 0.2882677 , 0.31123202,
        0.30392522, 0.1715424 , 0.93755612],
       [0.30653595, 0.86487783, 0.09504024, 0.93590822, 0.64106486,
        0.81496541, 0.12099329, 0.49363603],
       [0.20349274, 0.6386304 , 0.22040807, 0.78094032, 0.95823322,
        0.63439705, 0.55598415, 0.18235264]])

In [36]:
print(np.cov(arr))

[[ 0.08567154 -0.02817149  0.00271483 -0.0123241  -0.00098763]
 [-0.02817149  0.0827715   0.0595721   0.03377884  0.02593071]
 [ 0.00271483  0.0595721   0.07330257  0.04615029  0.01890943]
 [-0.0123241   0.03377884  0.04615029  0.08110026  0.02107597]
 [-0.00098763  0.02593071  0.01890943  0.02107597  0.02630454]]


In [37]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.31083632]
 [-0.31083632  1.        ]]


### compute cumulative sum & product

In [39]:
       1 3 5 6 8 9
csum = 1 4 9 15 23 32
cpro = 1 3 15 90 720 ... 

SyntaxError: invalid syntax (<ipython-input-39-d4a9cd301553>, line 1)

In [38]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.07699789 0.52920376 0.7749342  0.88254456 0.67506679 0.57745162
  0.10032377 0.58024666]
 [0.59347426 0.78172712 1.45870061 0.94270848 1.43247299 0.75375814
  0.78049291 0.67714599]
 [1.09986086 1.17330089 2.3811652  1.39232364 2.00538267 0.95616065
  1.35953669 0.69077561]
 [1.4647305  1.86065436 3.28595412 1.49693147 2.157208   1.29359436
  1.92668225 0.86823552]
 [1.92426634 2.56012851 4.01952478 1.9937673  2.93777457 2.07162761
  2.74670332 1.28881656]]


In [39]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.07699789 0.60620165 1.38113585 2.26368041 2.9387472  3.51619882
  3.6165226  4.19676926]
 [0.51647637 0.76899973 1.45276614 1.51293005 2.27033626 2.44664277
  3.12681191 3.22371123]
 [0.50638659 0.89796037 1.82042495 2.27004012 2.84294979 3.04535231
  3.62439609 3.63802571]
 [0.36486965 1.05222312 1.95701205 2.06161987 2.2134452  2.55087891
  3.11802447 3.29548439]
 [0.45953584 1.15900999 1.89258064 2.38941647 3.16998304 3.94801629
  4.76803737 5.18861841]]


In [40]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[7.69978878e-02 5.29203763e-01 7.74934202e-01 8.82544559e-01
  6.75066790e-01 5.77451620e-01 1.00323775e-01 5.80246662e-01]
 [3.97675900e-02 1.33636309e-01 5.29873976e-01 5.30973373e-02
  5.11299774e-01 1.01808483e-01 6.82371348e-02 5.62255095e-02]
 [2.01377744e-02 5.23284738e-02 4.88789978e-01 2.38733681e-02
  2.92928587e-01 2.06062932e-02 3.95122885e-02 7.66332348e-04]
 [7.34766265e-03 3.59681582e-02 4.42251759e-01 2.49734117e-03
  4.44739793e-02 6.95325795e-03 2.24092189e-02 1.35993275e-04]
 [3.37651432e-03 2.51587968e-02 3.24422912e-01 1.24076856e-03
  3.47149018e-02 5.40986586e-03 1.83760318e-02 5.71961928e-05]]


In [41]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[7.69978878e-02 4.07475720e-02 3.15766872e-02 2.78678334e-02
  1.88126489e-02 1.08633946e-02 1.08985675e-03 6.32385739e-04]
 [5.16476375e-01 1.30422346e-01 8.91784193e-02 5.36532299e-03
  4.06372891e-03 7.16461884e-04 4.87315259e-04 4.72205193e-05]
 [5.06386594e-01 1.98287709e-01 1.82913390e-01 8.22406342e-02
  4.71164550e-02 9.53648907e-03 5.52204469e-03 7.52633727e-05]
 [3.64869647e-01 2.50794419e-01 2.26916013e-01 2.37371911e-02
  3.60390686e-03 1.21607966e-03 6.89694176e-04 1.22393071e-04]
 [4.59535838e-01 3.21433439e-01 2.35794138e-01 1.17150975e-01
  9.14441359e-02 7.11465780e-02 5.83416937e-02 2.45374102e-02]]


### element-wise comparison

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [43]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
