In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,4)
arr

array([[0.15031551, 0.14857756, 0.48943311, 0.75169681],
       [0.32849617, 0.01819389, 0.27917183, 0.93711577],
       [0.75306167, 0.26811101, 0.60667641, 0.52436916]])

### transpose an array

In [4]:
# the following methods return a copy
print(arr.T)
print()
# or 
print("best")
print(np.transpose(arr)) # best way 
print()
# or
print(arr.transpose())

[[0.42841376 0.54121648 0.10836015]
 [0.36220365 0.63449683 0.55560188]
 [0.06704426 0.61310686 0.86184882]
 [0.31568781 0.89104114 0.55529824]]

best
[[0.42841376 0.54121648 0.10836015]
 [0.36220365 0.63449683 0.55560188]
 [0.06704426 0.61310686 0.86184882]
 [0.31568781 0.89104114 0.55529824]]

[[0.42841376 0.54121648 0.10836015]
 [0.36220365 0.63449683 0.55560188]
 [0.06704426 0.61310686 0.86184882]
 [0.31568781 0.89104114 0.55529824]]


### transpose of a high dimensional array with specified order of axes

In [6]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

print("-------------------------")
arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
-------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [7]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [9]:
#array : 16 --> 4*4 , 8*2 , 2*4*2
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.42841376, 0.36220365, 0.06704426, 0.31568781, 0.54121648,
        0.63449683],
       [0.61310686, 0.89104114, 0.10836015, 0.55560188, 0.86184882,
        0.55529824]])

In [14]:
# arr = [1,2,3] resize(2) -- > 1,2 
# arr = [[2,4,7 ] , [6,4,1 ] ] --> resize --> 2,2 --> [2,4] , [6,4 ]
# change the shape of an array in place
arr.resize((2,6))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### flatten an array

In [10]:
# return a copy
new = arr.flatten()
new.ndim # number of dimensions

1

In [11]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.42841376, 0.36220365, 0.06704426, 0.31568781, 0.54121648,
       0.63449683, 0.61310686, 0.89104114, 0.10836015, 0.55560188,
       0.86184882, 0.55529824])

### append elements to an array

In [12]:
arr = np.array([1,2,3])

In [14]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [15]:
arr

array([1, 2, 3])

In [16]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [17]:
arr

array([1, 2, 3])

### insert elements into an array

In [18]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [19]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [20]:
arr

array([1, 2, 3])

In [15]:
newarr = np.array([1,3,4])
newarr = np.insert(newarr,0, 5)
newarr

array([5, 1, 3, 4])

### delete elements from an array

In [21]:
arr

array([1, 2, 3])

In [22]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [23]:
arr

array([1, 2, 3])

In [24]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


In [25]:
arr

array([1, 2, 3])

### copy an array

In [3]:
arr = np.array([1,2,3])

In [4]:
arrx = arr

In [5]:
arrx 

array([1, 2, 3])

In [6]:
arrx[0] = 7

In [7]:
arrx

array([7, 2, 3])

In [8]:
arr

array([7, 2, 3])

In [ ]:
#note in c++: 

int x = 3; 
int y = x ; 
y = 4; 
cout << x << endl; // print 3 

# python (numpy ), same in pandas 

In [16]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)