In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [3]:
arr1 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
arr2 

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [5]:
arr1.shape

(2, 4)

### ```np.concatenate((a, b), axis=0)```

In [6]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [7]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [6]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [7]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [8]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [9]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [10]:
arr = np.random.rand(6,6)
arr

array([[0.90788294, 0.5547824 , 0.19436083, 0.44082175, 0.8721725 ,
        0.00821049],
       [0.43920149, 0.8568443 , 0.46662853, 0.47041953, 0.8908432 ,
        0.51568584],
       [0.56952621, 0.6351557 , 0.65715564, 0.14615993, 0.3463577 ,
        0.75020858],
       [0.66198303, 0.45153232, 0.01660063, 0.83831183, 0.0476893 ,
        0.50079196],
       [0.79746569, 0.506837  , 0.15293153, 0.0903732 , 0.35506753,
        0.35023582],
       [0.0975391 , 0.49950143, 0.04867677, 0.92633821, 0.25913252,
        0.92628562]])

In [17]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(len(arr1))
print(arr1[0].shape)
print(arr1[1].shape)
print(arr1)

2
(3, 6)
(3, 6)
[array([[0.90788294, 0.5547824 , 0.19436083, 0.44082175, 0.8721725 ,
        0.00821049],
       [0.43920149, 0.8568443 , 0.46662853, 0.47041953, 0.8908432 ,
        0.51568584],
       [0.56952621, 0.6351557 , 0.65715564, 0.14615993, 0.3463577 ,
        0.75020858]]), array([[0.66198303, 0.45153232, 0.01660063, 0.83831183, 0.0476893 ,
        0.50079196],
       [0.79746569, 0.506837  , 0.15293153, 0.0903732 , 0.35506753,
        0.35023582],
       [0.0975391 , 0.49950143, 0.04867677, 0.92633821, 0.25913252,
        0.92628562]])]


In [18]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2[0].shape)
print(arr2[1].shape)
print(arr2)

(6, 3)
(6, 3)
[array([[0.90788294, 0.5547824 , 0.19436083],
       [0.43920149, 0.8568443 , 0.46662853],
       [0.56952621, 0.6351557 , 0.65715564],
       [0.66198303, 0.45153232, 0.01660063],
       [0.79746569, 0.506837  , 0.15293153],
       [0.0975391 , 0.49950143, 0.04867677]]), array([[0.44082175, 0.8721725 , 0.00821049],
       [0.47041953, 0.8908432 , 0.51568584],
       [0.14615993, 0.3463577 , 0.75020858],
       [0.83831183, 0.0476893 , 0.50079196],
       [0.0903732 , 0.35506753, 0.35023582],
       [0.92633821, 0.25913252, 0.92628562]])]
